### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by pierluigi** [octodemo/github-craftwork-azure#1]
TODOs

- [x] @pierluigi or @svanboxel update pipeline to release only from master
- [x] update readme with updated instructions
- [x] @bas  create slides for intro / outro
- [x] @svanboxel update basic example with label
- [x] @bas create branch with LUIS changes
- [x] @svanboxel add real tests to function
- [x] general code polish up (edited)

**Comment by SvanBoxel** [comment]
Good to know:

Invoiced customers will not be able to directly install Azure Pipelines from the marketplace. Instead they can visit the apps page and install it from there: https://github.com/apps/azure-pipelines/

**Comment by pierluigi** [comment]
Demo of the final result

![out](https://user-images.githubusercontent.com/1078545/46737809-c5c84100-cc9c-11e8-8536-89cddf33049e.gif)
